version: 2.1
orbs:
  node: circleci/node@volatile
jobs:
  chromedriver:
    docker:
      - image: cimg/node:current-browsers # pre-baked with selenium
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run: yarn test
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - chromedriver